namespace: community
name: zabbix
version: 0.1.0
readme: README.md
authors:
- Dusan Matejka (@D3DeFi)
- sky-joker (@sky-joker)
description: Collection allowing to configure resources in Zabbix monitoring system
license_file: LICENSE
tags:
  - monitoring
  - zabbix
dependencies: {}
repository: https://github.com/ansible-collections/community.zabbix.git
documentation: https://github.com/ansible-collections/community.zabbix.git
homepage: https://github.com/ansible-collections/community.zabbix
issues: https://github.com/ansible-collections/community.zabbix/issues
