name: CI
on:
#- pull_request
- push

jobs:
#  sanity:
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Check out code
#        uses: actions/checkout@master
#        #with:
#        #  path: ansible_collections/community/zabbix
#
#      - name: Set up Python 3.6
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.6
#
#      - name: Install ansible-base
#        run: pip install git+https://github.com/ansible-collection-migration/ansible-base.git --disable-pip-version-check
#
#      - name: Run sanity tests
#        run: ansible-test sanity --docker -v --color --python 3.6

#  integration:
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Check out code
#        uses: actions/checkout@master
#        with:
#          path: ansible_collections/community/zabbix
#
#      - name: Set up Python 3.6
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.6
#
#      - name: Install dependencies
#        run: pip install docker-compose zabbix-api
#
#      - name: zabbix container server provisioning
#        run: docker-compose -f ansible_collections/community/zabbix/docker-compose.yml up -d
#
#      - name: Install ansible-base
#        run: pip install git+https://github.com/ansible-collection-migration/ansible-base.git --disable-pip-version-check
#
#      - name: run integration test
#        run: |
#          cd ansible_collections/community/zabbix
#          ansible-test integration -v --color --retry-on-error --continue-on-error --diff

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zabbix_container:
          - version: "3.0"
            port: "80"
          - version: "4.0"
            port: "80"
          - version: "4.4"
            port: "80"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: sample02
          path: ansible_collections/community/zabbix

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: pip install docker-compose zabbix-api

      - name: zabbix container server provisioning
        run: docker-compose -f ansible_collections/community/zabbix/docker-compose.yml up -d
        env:
          zabbix_version: ${{ matrix.zabbix_container.version }}
          zabbix_port: ${{ matrix.zabbix_container.port }}

      - name: Install ansible-base
        run: pip install git+https://github.com/ansible-collection-migration/ansible-base.git --disable-pip-version-check

      - name: run integration test
        run: |
          cd ansible_collections/community/zabbix
          ansible-test integration -v --color --retry-on-error --continue-on-error --diff
